eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   #defaultZone:http://192.168.10.118:8761/eureka/
      
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hellocaishen/SCRM/
          searchPaths: application*  #application*
          username: 1357023600@qq.com
          password: #password
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: git
server:
  port: 8081
management:
  security:
    enabled: true


